"""Writes src/styles/kana.css: BIZ UDPMincho restricted to kana, as the family
"Kotoba Kana". Listed before BIZ UDPGothic, it gives Japanese text the アンチック体
mix manga lettering uses (kanji in gothic, kana in mincho). Rerun after updating
@fontsource/biz-udpmincho."""
import re
from pathlib import Path

KANA = (0x3041, 0x30FF)
root = Path(__file__).resolve().parent.parent
pkg = root / "node_modules/@fontsource/biz-udpmincho"
out = ["/* generated by scripts/kana-font.py */"]
for weight in (400, 700):
    css = (pkg / f"{weight}.css").read_text()
    for block in re.findall(r"@font-face\s*{(.*?)}", css, re.S):
        ranges = []
        for part in re.search(r"unicode-range:\s*([^;]+);", block)[1].split(","):
            a, _, b = part.strip()[2:].partition("-")
            a, b = int(a, 16), int(b or a, 16)
            lo, hi = max(a, KANA[0]), min(b, KANA[1])
            if lo <= hi:
                ranges.append(f"U+{lo:X}" + (f"-{hi:X}" if hi > lo else ""))
        if not ranges:
            continue
        file = re.search(r"url\(\./files/([^)]+\.woff2)\)", block)[1]
        out.append("@font-face {\n  font-family: 'Kotoba Kana';\n  font-style: normal;\n"
                   f"  font-display: swap;\n  font-weight: {weight};\n"
                   f"  src: url(../../node_modules/@fontsource/biz-udpmincho/files/{file}) format('woff2');\n"
                   f"  unicode-range: {', '.join(ranges)};\n}}")
(root / "src/styles/kana.css").write_text("\n".join(out) + "\n")
print(len(out) - 1, "faces")
