# Generated by Django 6.1.2 on 2026-10-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleanup',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cleanup', serialize=False, to='library.source')),
                ('words', models.JSONField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('script', models.TextField(blank=True)),
                ('cuts', models.JSONField(blank=True, null=True)),
                ('peaks', models.JSONField(blank=True, null=True)),
                ('clean', models.FileField(blank=True, upload_to='clean/')),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
